const val RETRO_ARCH_CORE_EXTENSION = "dll"
const val RETRO_ARCH_LIST_SUBDIR = "playlists"
const val RETRO_ARCH_CORES_SUBDIR = "cores"
const val RETRO_ARCH_LIST_EXTENSION = "lpl"
const val PLAYLIST_VERSION = "1.5"

const val LANGUAGE_ENGLISH = "English"
const val LANGUAGE_SERBIAN = "Srpski"

const val ENGLISH_LANGUAGE_CODE = "en"
const val SERBIAN_LANGUAGE_CODE = "sr"

const val GITHUB_LINK = "https://github.com/bnovakovic/gamelistmanager"
const val RECALBOX_LINK = "https://www.recalbox.com"
const val RETROPIE_LINK = "https://retropie.org.uk"
const val RETROARCH_LINK = "https://www.retroarch.com"
const val GAME_LIST_EDITOR_LINK = "https://github.com/andresdelcampo/GameList_Editor"
const val SCREEN_SCRAPPER_LINK = "https://www.screenscraper.fr/"
const val KOTLIN_MULTIPLATFORM_LINK = "https://kotlinlang.org/docs/multiplatform.html"
const val KMP_NAME = "Kotlin Multiplatfrom (KMP)"
const val RECALBOX = "Recalbox"
const val RETROPIE = "Retropie"
const val RETRO_ARCH = "RetroArch"
const val SCREEN_SCRAPPER = "Screen Scrapper"
const val GAME_LIST_EDITOR = "GameList Editor"